openapi: 3.1.0
info:
  title: Pixelixe Authentication API
  version: '2.0'
  description: '

    High-quality and ultra-fast Image Editing API. Resize, Crop, Flip, Rotate,

    Contrast, Opacify, Blur and transform your photos with APIs.'
servers:
- url: https://studio.pixelixe.com/api
security:
- bearerAuth: []
tags:
- name: Authentication
paths:
  /authentication/v2:
    get:
      summary: Pixelixe Authenticate API Key
      description: Validates the API key provided in the Authorization header.
      responses:
        '200':
          description: Successful authentication.
          content:
            application/json:
              example:
                status: success
                message: Authenticated successfully
      tags:
      - Authentication
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
